version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: >
      sh -c "sh entrypoint.sh"
    environment:
      - FOO=BAR
