version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    command: >
      sh -c "sh entrypoint.sh"
    env_file:
      - .env
